const {Game} = require('../classes/Game')
const {Player} = require('../classes/Player')
const player = new Player("Player", "abcd")
const deck = [
    'spades:8',    'spades:J',  'spades:A',   'diamonds:6',
    'clubs:6',     'clubs:8',   'diamonds:J', 'clubs:7',
    'spades:5',    'hearts:6',  'hearts:9',   'clubs:10',
    'hearts:K',    'hearts:Q',  'diamonds:9', 'hearts:5',
    'diamonds:Q',  'clubs:3',   'spades:Q',   'clubs:9',
    'hearts:8',    'clubs:Q',   'clubs:J',    'clubs:5',
    'hearts:3',    'spades:10', 'hearts:J',   'diamonds:4',
    'clubs:K',     'spades:6',  'diamonds:2', 'diamonds:A',
    'diamonds:7',  'spades:K',  'diamonds:5', 'diamonds:K',
    'hearts:4',    'hearts:A',  'spades:4',   'spades:2',
    'diamonds:10', 'hearts:10', 'spades:9',   'diamonds:3',
    'spades:3',    'clubs:A',   'clubs:2',    'hearts:2',
    'diamonds:8',  'spades:7',  'hearts:7',   'clubs:4'
]
beforeEach(() => {
    
return game = new Game("efgh",player, deck)
})

test('Player(correct values)', () => {
    expect({id: player.id, nick:player.nick}).toEqual({id: "abcd", nick:"Player"})
})

test('Game(correct values)', () => {
    expect({id: game.id, players: game.players, deck: game.deck, status: game.status, pile: game.pile})
    .toEqual({id:"efgh", players: [player], deck: deck, status: 'waiting', pile: []})
})
test('Game.join(correct player)', () => {
    const player2 = new Player("Player2", "ijkl")
    game.join(player2)
    expect(game.players[1]).toEqual(new Player("Player2", "ijkl"))
})
test('Game.join(players length)', () => {
    const player2 = new Player("Player2", "ijkl")
    game.join(player2)
    expect(game.players.length).toEqual(2)
})
test('Game.join(game started)', () => {
    const player2 = new Player("Player2", "ijkl")
    game.join(player2)
    game.start()
    const player3 = new Player("Player3", "mnop")
    game.join(player3)
    expect(game.players.length).toEqual(2)
})
test('Game.start(correct turn index/last to first index)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.start()
    expect(game.turn).toEqual(0)
})
test('Game.start(correct turn index/next index)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    expect(game.turn).toEqual(3)
})
test('Game.start(start pile value)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    game.join(player2)
    game.join(player3)
    game.start()
    expect(game.pile[0]).toEqual("hearts:2")
})
test('Game.move(1 card)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.start()
    game.move(0, ["spades:3"], '3')
    expect(game.pile[0]).toEqual("spades:3")
})
test('Game.move(2 cards)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.start()
    game.move(0, ["spades:3","spades:5"], '5')
    expect([game.pile[0], game.pile[1]]).toEqual(["spades:3", "spades:5"])
})
test('Game.move(4 cards)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.start()
    game.move(0, ["spades:3","spades:5", "hearts:3", "diamonds:7"], '3')
    expect(game.pile.length).toEqual(5)
})
test('Game.move(game not started)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.move(0, ["spades:3"], '3')
    expect(game.pile.length).toEqual(0)
})
test('Game.move(declared value lower than actual)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.start()
    game.move(0, ["spades:3"], '3')
    game.move(1, ["spades:2"], '2')
    expect(game.pile[0]).toEqual("spades:3")
})
test('Game.check(not lying)', () => {
    const player2 = new Player("Player2", "ijkl")
    game.join(player2)
    game.start()
    game.move(0, ["clubs:2","spades:3","diamonds:2","diamonds:5"],'5')
    game.move(1, ["spades:2","clubs:3","diamonds:3"],'6')
    game.move(0, ["diamonds:J"],'J')
    game.check(1)
    expect(game.players[1].hand.length).toEqual(30)
})
test('Game.check(not lying, other player check)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6', 'spades:5'], '5')
    game.move(4, ['clubs:6', 'hearts:6'], '6')
    game.move(0, ['hearts:7'],'7')
    game.check(3)
    expect(game.players[3].hand.length).toEqual(13)
})
test('Game winning(empty hand)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6', 'spades:5'], '5')
    game.players[3].hand = []
    expect(game.winners.length).toEqual(0)
})
test('Game winning(empty hand next player moves)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6', 'spades:5'], '5')
    game.players[3].hand = []
    game.move(4, ['clubs:6', 'hearts:6'], '6')
    expect(game.winners.length).toEqual(1)
})
test('Game winning(winning player cheated, next player check and moves)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6', 'spades:5'], 'K')
    game.players[3].hand = []
    game.check(4)
    game.move(4, ['clubs:6', 'hearts:6'], '6')
    expect(game.winners.length).toEqual(0)
})
test('Game winning(winning player cheated, next player check)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6', 'spades:5'], 'K')
    game.players[3].hand = []
    game.check(4)
    expect(game.winners.length).toEqual(0)
})
test('Game winning(winning player cheated, other player check and next moves)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6', 'spades:5'], 'K')
    game.players[3].hand = []
    game.check(0)
    game.move(4, ['clubs:6', 'hearts:6'], '6')
    expect(game.winners.length).toEqual(0)
})
test('Game winning(winning player cheated, other player check and next moves)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6', 'spades:5'], 'K')
    game.players[3].hand = []
    game.check(0)
    game.move(4, ['clubs:6', 'hearts:6'], '6')
    expect(game.winners.length).toEqual(0)
})
test('Game winning(winning player not cheated, other player check)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6'], '6')
    game.players[3].hand = []
    game.check(0)
    expect(game.winners.length).toEqual(0)
})
test('Game winning(winning player not cheated, other player check and next moves)', () => {
    const player2 = new Player("Player2", "ijkl")
    const player3 = new Player("Player3", "mnop")
    const player4 = new Player("Player4", "vcnm")
    const player5 = new Player("Player5", "pcop")
    game.join(player2)
    game.join(player3)
    game.join(player4)
    game.join(player5)
    game.start()
    game.move(3, ['diamonds:6'], '6')
    game.players[3].hand = []
    game.check(0)
    game.move(4, ['clubs:6', 'hearts:6'], '6')
    expect(game.winners.length).toEqual(1)
})